from django.conf.urls import url
from catalog import views

urlpatterns = [
<<<<<<< HEAD
    url(r'^$', views.tasks_list,
        name='root'),
    url(r'^create_task/', views.create_task,
        name='create_task'),
    url(r'^task/(?P<pk>\d+)/$', views.TaskDetailView.as_view(),
        name='task-detail'),
    url(r'^task/(?P<pk>\d+)/create_description/$', views.create_description,
        name='create_description'),
    url(r'^task/(?P<pk>\d+)/update/$', views.update_task,
        name='update_task'),
    url(r'^task/(?P<pk>\d+)/delete/$', views.delete_task,
        name='delete_task'),
    url(r'^API/users/$', views.UserList.as_view(),
        name='users-list'),
    url(r'^API/users/(?P<pk>\d+)/$', views.UserDetail.as_view(),
        name='user-detail'),
    url(r'^API/projects/(?P<pk>\d+)/$', views.ProjectDetail.as_view(),
        name='project-detail'),
    url(r'^API/tasks/$', views.TasksList.as_view(),
        name='tasks-list'),
    url(r'^API/tasks/(?P<pk>\d+)/$', views.TaskDetail.as_view(),
        name='api-task-detail'),
    url(r'^API/tasks/(?P<pk>\d+)/descriptions/$',
        views.DescriptionList.as_view(),
        name='description-detail'),
    url(r'^API/tasks/(?P<pk>\d+)/descriptions/(?P<id>\d+)/$',
        views.DescriptionDetail.as_view(),
        name='task-descriptions'),
    url(r'^API/tasks/(?P<pk>\d+)/descriptions_statistic/$',
        views.DescriptionStatistics.as_view(),
        name='descriptions_statistic'),
=======
    url('^$', views.tasks_list),
    url('^create_task/', views.create_task),
    url(r'^task/(?P<pk>\d+)$', views.TaskDetailView.as_view(), name = 'task-detail'),
    url(r'task/(?P<pk>\d+)/create_description/$', views.create_description),
    url(r'task/(?P<pk>\d+)/update/$', views.update_task),
    url(r'task/(?P<pk>\d+)/delete/$', views.delete_task),
>>>>>>> 6f8fe3e3c48cb7df81d56b22aea08c3df06c58ec
]
