# Generated by Django 2.2 on 2019-04-16 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('prog', 'In progress'), ('ready', 'Ready'), ('compile', 'Completed'), ('cancel', 'Canceled'), ('test', 'Being tested')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Users')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Projects')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='catalog.Users')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Users'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.Tasks')),
            ],
        ),
    ]
