# Generated by Django 2.2 on 2019-04-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190420_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.Users'),
            preserve_default=False,
        ),
    ]
