# Generated by Django 2.2 on 2019-04-22 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190421_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tasks'),
        ),
    ]
